name: Suggest an Oracle
description: Suggest an Oracle for developers to use when building with Optimism
title: Suggest an Oracle
labels: ["documentation,oracle,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read the [listing of current Oracles](https://snazzy-hamster-4e1647.netlify.app/tools/oracles).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: input
    id: oracle_name
    attributes:
      label: Oracle Name
    validations:
      required: true
  - type: textarea
    id: oracle_description
    attributes:
      label: Oracle Description
    validations:
      required: true
  - type: input
    id: oracle_URL
    attributes:
      label: Oracle URL
      description: Please provide the URL for us to link in the project description above.
    validations:
      required: true
  - type: checkboxes
    id: oracle_type
    attributes:
      label: Oracle Type
      options:
        - "push oracle"
        - "pull oracle: double transaction"
        - "pull oracle: single transaction"
    validations:
      required: true
  - type: input
    id: oracle_live_date
    attributes:
      label: When did the product go live?
      description: We prioritize products that are battle-tested.
    validations:
      required: true
  - type: dropdown
    id: oracle_open_source
    attributes:
      label: Is the product open source?
      description: We prioritize open source projects when possible.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: oracle_github
    attributes:
      label: GitHub URL
      description: If the project is open source, please provide a link to the product's repo.
  - type: input
    id: oracle_docs
    attributes:
      label: Documentation URL
      description: Please provide a link to the product's technical documentation.
    validations:
      required: true
  - type: textarea
    id: oracle_additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the product here.
  - type: checkboxes
    id: oracle_work_on
    attributes:
      label: Would you like to work on this issue?
      options:
        - label: "Yes"
          required: false
        - label: "No"
          required: false
    validations:
      required: true
