name: Suggest a faucet
description: Suggest a faucet for developers to use when building with Optimism
title: "[FAUCET] Add PR title"
labels: ["documentation,faucet,community-request"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this suggestion, be sure to read the [listing of current Faucets](https://snazzy-hamster-4e1647.netlify.app/tools/faucets).
  - type: markdown
    id: project_info
    attributes:
      value: "## Project Info"
  - type: input
    id: faucet_name
    attributes:
      label: Faucet Name
    validations:
      required: true
  - type: textarea
    id: faucet_description
    attributes:
      label: Faucet Description
    validations:
      required: true
  - type: input
    id: faucet_URL
    attributes:
      label: Faucet URL
      description: Please provide the URL for us to link in the project description above.
    validations:
      required: true
  - type: checkboxes
    id: faucet_networks
    attributes:
      label: Supported Networks
      options:
        - label: "OP Mainnet"
          required: false
        - label: "OP Goerli"
          required: false
        - label: "OP Sepolia"
          required: false
    validations:
      required: true
  - type: input
    id: faucet_live_date
    attributes:
      label: When did the product go live?
      description: We prioritize products that are battle-tested.
    validations:
      required: true
  - type: dropdown
    id: faucet_open_source
    attributes:
      label: Is the product open source?
      description: We prioritize open source projects when possible.
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: input
    id: faucet_github
    attributes:
      label: GitHub URL
      description: If the project is open source, please provide a link to the product's repo.
  - type: textarea
    id: faucet_additional_context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the product here.
